# GitHub Action: Build & Push Docker image to Docker Hub
# Requires two repository secrets:
#   DOCKERHUB_USERNAME – your Docker Hub username (e.g. xpert123)
#   DOCKERHUB_TOKEN    – a Personal Access Token with "write:push" scope
#
# On every push to main (or when Docker-related files change) this will
# build the image and push the tag `latest`.
# Adjust the `tags:` value if you need versioned tags.

name: Docker Image CI

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "**/*.py"
      - ".github/workflows/docker-publish.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: xpert123/chris2004m:latest
